#include <iostream>
using namespace std;

int main() {

   cout << "elephant " << endl;
   cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << endl;
   cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << endl;
   cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << endl;
   cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << endl;
   cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << endl;
   cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXXKXXXXKXWMMMMMMMMMMMMMMMWMMMMWXKKKXXKXXWMMMMMMMMMMM" << endl;
   cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXK00000000KXNWWWXNWNXXNWNXNWNWWNXK0000000KXNWMMMMMMMMM" << endl;
   cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXoxWMMMMMMMMMOo0W0kkxxxkxxxkkk0WOo0MMMMMMMMNxoXWMMMMMMMM" << endl;
   cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXooXMMMMMMMMMMNxl0WWWNNWWNNWMNNWOcxWMMMMMMMMMXloXWMMMMMMM" << endl;
   cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOxXMMMMMMMMMMMWNkxNMWMMMMMMMMMMNxkWMMMMMMMMMMMXxOWWMMMMMM" << endl;
   cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNWWWMMMMMMMMMMMMMMMWWMMMMMMMMMMMMWWWMMMMMMMMMMMMMWWWNWMMMMM" << endl;
   cout << "MMMMMMMMMMMMMMMMMMMMMWNNNWNNNWNNNWWNNNWKdOWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMWkdKMMMM" << endl;
   cout << "MMMMMMMMMMMMMMMMMWXXWNK0XNK0KNX00XXK0KNdcXMMMMMMMMMMMMMMMMMMMMMMMMMXXWMNKXMMMMMMMMMMMMMMMMMMMKcxMMMM" << endl;
   cout << "MMMMMMMMMMMMMMMMMNdoXMMMMMMMMMMMMMMWMMM0lOWMMMMMMMMMMMMMMMMMMMMMMMW0kXMXx0WMMMMMMMMMMMMMMMMMWkl0MMMM" << endl;
   cout << "MMMMMMMMMMMMMMWNWWNNWMMMMMMMMMMMMMMMMMMWXXWNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNWXXWMMMM" << endl;
   cout << "MMMMMMMMMMMMMWkdXMMMMMMMMMMMMMMMMMMMMMMMMMWkdKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKokWMMMMMMM" << endl;
   cout << "MMMMMMMMMMMMWkl0WMMMMMMMMMMMMMMMMMMMMMMMMWMNolXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWKldNMMMMMMMM" << endl;
   cout << "MMMMMMMMMMMWKd0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdxXXXXXXXXXNWWWMMMMMMMMMMMMMMMMMMWNXXXXXXXXxxNMMMMMMMMM" << endl;
   cout << "MMMMMMMMMMWNWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNX00000000KNWNWWNWMMMMMMMMMMMWNWNK0OO0O00KNWMMMMMMMMMM" << endl;
   cout << "MMMMMMMMMXdkWOoKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWkdXXdkWMMMMMMMMMMXokMNkxNMMMMMMWMMMMMMMMMM" << endl;
   cout << "MMMMMMMMXooXWx:0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:dWWOckWMMMMMMMMMK:dMO:xWWWMMMMMMMMMMMMMMM" << endl;
   cout << "MMMMMMMWkdXWWx:0MMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMWMMMMMMMMNdoXMWOdKWMMMMMMMM0:dMXodXMMMMMMMMMMMMMMMMM" << endl;
   cout << "MMMWKk0WWWWMW0OXMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMWWMMMMMMMMMNXNMMWNNWWMMMMMMMNk0MMNKNMMMMMMMMMMMMMMMMM" << endl;
   cout << "MMMN0kOXMMMW0d0MMMMMMMMMMMMMMMMXdOWWMMMMMMMMMMMKdOWWMMMMMMMMMMW0d0kdXMMMMMMXokMMMMMMMMMMMMMMMMMMMMMM" << endl;
   cout << "MMMMMMMMMMMWWkl0MMMMMMMMMMMMMWXooXWWMMMMMMMMMMMWkcl0MWMMMWMMMM0ckWXloNMMMMM0:dMMMMMMMMMMMMMMMMMMMMMM" << endl;
   cout << "MMMMMMMMMMMMMWkdXMMMMMMMMMMMMNxdXWNNNNNNNNNNNNNWWkcdXMMMMWWMMXdkWWWKokWWWMM0:dWMMMMMMMMMMMMMMMMMMMMM" << endl;
   cout << "MMMMMMMMMMMMMMWNWWWWMMMMMMMMMWNNWWK00000000000KNMNXNWMMMMMMWWWNNWWWWWNWWWWWNO0MMMMMMMMMMMMMMMMMMMMMM" << endl;
   cout << "MMMMMMMMMMMMMMMWMXdkMMMMMMMMMWNxkWMMMMMMMMMMMMMM0dd0WMMMMMMMMMKoOWWWWW0kOkKMMMMMMMMMMMMMMMMMMMMMMMMM" << endl;
   cout << "MMMMMMMMMMMMMMMMMKcdMMMMMMMMWMNcoWMMMMMMMMMMMMMMx:cOMMMMMMMMMMO;xWXK0XNXNNWMMMMMMMMMMMMMMMMMMMMMMMMM" << endl;
   cout << "MMMMMMMMMMMMMMMMMK:dWNNNNNNNNWNloWMMMMMMMMMMMMMMk;cOWNNNNNNNNWO;xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << endl;
   cout << "MMMMMMMMMMMMMMMMMNO0WK0000000XN00WMMMMMMMMMMMMMMKkOXNK0000000NXkKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << endl;
   cout << "MMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << endl;
   cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << endl;
   cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << endl;
   cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << endl;
   cout << "MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM" << endl;




  
   return 0;
}